# Generated by Django 2.2.9 on 2020-01-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer_Buyer_Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerbuyeraccount',
            name='Farm_City',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
