# Generated by Django 2.2.9 on 2020-01-19 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CropGenre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellHarvestedCrops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0, help_text='In tonnes')),
                ('Farm_image', models.ImageField(blank=True, upload_to='farm_image')),
                ('Harvest_Variety', models.CharField(blank=True, max_length=100)),
                ('Harvest_Description', models.CharField(blank=True, max_length=500)),
                ('quality', models.CharField(blank=True, choices=[('P', 'PREMIUM'), ('VG', 'VERY GOOD'), ('G', 'GOOD'), ('JR', 'JUST RIGHT')], default='P', help_text='Quality of crop', max_length=2)),
                ('Crop_Name', models.ForeignKey(on_delete='CASCADE', related_name='sellCrops', to='MarketPlace.Crops')),
                ('Harvest_Type', models.ForeignKey(on_delete='CASCADE', related_name='crops', to='MarketPlace.HarvestType')),
                ('sold_by', models.ForeignKey(on_delete='CASCADE', related_name='farmers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
