# Generated by Django 2.2.9 on 2020-01-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Crop_Name', models.CharField(blank=True, max_length=100)),
                ('Image', models.ImageField(blank=True, upload_to='farm_image')),
                ('quality', models.CharField(blank=True, choices=[('P', 'PREMIUM'), ('VG', 'VERY GOOD'), ('G', 'GOOD'), ('JR', 'JUST RIGHT')], default='P', help_text='Quality of crop', max_length=2)),
                ('quantity', models.CharField(blank=True, choices=[('10 kg', 'PREMIUM'), ('20 kg', 'VERY GOOD'), ('30 kg', 'GOOD'), ('40 kg', 'JUST RIGHT')], default='P', help_text='Quality of crop', max_length=2)),
                ('Crop_Description', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
