# Generated by Django 3.0.2 on 2020-01-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.FileField(upload_to='vegetables/photos')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
